export const PROJECT_SEED_DATA = [
  {
    number: 1,
    title: "The Vibe Code Kickoff",
    subtitle: "Build Your Resolution Tracker",
    deliverable: "A working web app that tracks your progress through these 10 weekends.",
    description_work: "Build it: Use Replit Agent, Lovable, or Cursor to create a simple tracker app. Core Features: List of all 10 weekends, completion checkboxes, notes field, progress bar. Ship it: Deploy live. Use it: Log Weekend 1 as 'Complete' before closing laptop.",
    description_advanced: "Add user authentication for multi-user support. Build as a PWA for mobile access. Add 'suggest next weekend' logic. Add time-tracking field.",
    done_when: "Your tracker is live on the internet, you've logged Weekend 1, and you trust you'll actually use it.",
    why_it_matters: "You start by proving to yourself that you can build something functional with AI. That psychological shift — from 'I'm not a coder' to 'I built this' — makes everything else possible.",
    sort_order: 1,
  },
  {
    number: 2,
    title: "The Model Mapping Project",
    subtitle: "Build Your Personal AI Topography",
    deliverable: "Model Topography Sheet + 'AI Rules of Thumb' document.",
    description_work: "Pick 2-3 Models: Use what you have (Claude, ChatGPT, Gemini). Run Tests: Run the same task through each: Deep Research, Writing, Strategy, Data, Visual. Compare: Which felt right? Which was faster? Which asked better questions? Synthesize: Create a one-page 'Rules of Thumb'.",
    description_advanced: "Test specialized tools (Perplexity, etc.). Build a matrix including cost & context window. Test output consistency over time. Track 'editing time' needed per model.",
    done_when: "You can answer 'which tool do I use for what?' in 30 seconds without hesitation.",
    why_it_matters: "Most people default to one AI model for everything, leaving capability on the table. The goal isn't 'which model is objectively best' — it's developing your own instincts.",
    sort_order: 2,
  },
  {
    number: 3,
    title: "The Deep Research Sprint",
    subtitle: "Let AI Do a Week's Research in an Afternoon",
    deliverable: "A 2-page research brief with a clear recommendation on a real decision.",
    description_work: "Real Question: Pick a decision you actually need to make (not hypothetical). Deep Tools: Use Claude, Gemini, or ChatGPT deep research modes. Iterate: Push back. Ask for disconfirming evidence. Don't accept first output. Structure: Problem, Findings, Options, Recommendation, Risks.",
    description_advanced: "Run the same question through all 3 major tools. Create a meta-analysis of which tool was most accurate. Build a 'Fact Check List' of 10 claims you verify manually.",
    done_when: "Your brief leads to a recommendation you'd actually follow, with known uncertainties.",
    why_it_matters: "Deep research is the capability most people have heard about but few have stress-tested. The gap between 'AI can do research' and 'I trust this enough to make a decision' is where this weekend lives.",
    sort_order: 3,
  },
  {
    number: 4,
    title: "The Analysis Project",
    subtitle: "Turn Messy Data Into Actual Decisions",
    deliverable: "A cleaned dataset + a one-page Insights Memo with specific actions.",
    description_work: "Collect: Gather real data (CSV/spreadsheet) from Spotify, bank, Google Takeout, or Kaggle. Upload: Use Claude or ChatGPT to propose cleaning steps, 5-10 metrics, and 3 hypotheses. Produce: Cleaned dataset, summary table, 3 insights, 3 actions. Write: A one-page Insights Memo (no charts required).",
    description_advanced: "Build a reusable prompt template for monthly updates. Connect to a live data source for real-time analysis. Compare insights from Claude vs. ChatGPT on the same data.",
    done_when: "You can name the top 3 drivers of whatever you analyzed and what you're going to do about them.",
    why_it_matters: "This is where most people hit the gap between 'AI can analyze data' and actually doing it. Most people have never uploaded their own spreadsheet and pushed into 'what should I do about this?' territory.",
    sort_order: 4,
  },
  {
    number: 5,
    title: "The Visual Reasoning Project",
    subtitle: "Make AI See and Think",
    deliverable: "One infographic, diagram, or visual explainer you'd actually use — not a demo.",
    description_work: "Concept: Pick a process, comparison, framework, or timeline. Reasoning: Ask AI 'What is the best logic to visualize this? What are the tradeoffs?' Draft: Generate 2 alternate design approaches (e.g. flowchart vs matrix). Finalize: Build it using AI generation or tools like Canva/Gamma. Visual QA: Readable in 5s? One clear takeaway?",
    description_advanced: "Create a reusable visual system or template. Design and build a complex data visualization. Build a 'visual pattern library' (2x2s, cycles, flows).",
    done_when: "You can explain the idea faster with the visual than with words, and others get the point instantly.",
    why_it_matters: "Most people use AI just to 'make pictures.' The real skill is Visual Reasoning: getting AI to think through the logic of visual communication. It's not about art; it's about explaining complex ideas instantly.",
    sort_order: 5,
  },
  {
    number: 6,
    title: "The Information Pipeline",
    subtitle: "Build Your NotebookLM + Gamma Stack",
    deliverable: "A reusable workflow: Summary + FAQ + Presentation Deck from one input source.",
    description_work: "Input: Take a corpus (transcript, report, notes, or book). NotebookLM: Generate summary, glossary, FAQ, and audio overview. Gamma: Create 8-12 slide deck with 1 visual & clear recommendation. Document: Save the prompts and workflow to repeat later.",
    description_advanced: "Build full repurposing pipeline (Audio, Deck, One-pager, Tweets). Time the process & compare to manual effort. Create a reusable checklist template.",
    done_when: "You can brief someone on the material in under 7 minutes using your deck.",
    why_it_matters: "NotebookLM and Gamma are criminally underused. Most people try them once, then forget. This weekend builds them into your actual workflow.",
    sort_order: 6,
  },
  {
    number: 7,
    title: "The First Automation",
    subtitle: "Build Your Content Distribution Machine",
    deliverable: "One working automation handling production or distribution + a 'How It Works' doc.",
    description_work: "Components: Must have Trigger, Transform, Route, Approval, and Logging. Tools: Use Lindy, n8n, Make, or native Slack/Notion workflows. Build: E.g., Notion note → Summarize → Draft Tweets → Send to Slack. Default: Weekly Reading Digest (summarize saved links, email digest).",
    description_advanced: "Chain multiple automations together. Add conditional logic for different content types. Add robust error handling for failures. Log detailed analytics.",
    done_when: "You've run it twice successfully, it saved you time, and you can explain it.",
    why_it_matters: "This is where leverage starts compounding. One automation that saves 30 minutes per piece of content × 50 pieces per year equals massive time back.",
    sort_order: 7,
  },
  {
    number: 8,
    title: "The Second Automation",
    subtitle: "Build Your Productivity Workflow",
    deliverable: "One working productivity automation + a follow-up dashboard or tracker.",
    description_work: "Components: Trigger → Transform → Route → Approval → Logging. Pick One: Inbox → Follow-up OR Lead → Response OR Meeting Prep Bot. Default: Prep Bot (Calendar event → LinkedIn lookup + History check → Briefing sent 30m before). Platform: Use Lindy, n8n, Make, or Zapier.",
    description_advanced: "Add a feedback loop to rate output quality. Make it conversational (e.g., Slack bot drafts reply, you say 'send'). Connect to CRM/tracker for dashboard view.",
    done_when: "The system creates follow-ups automatically, you trust it enough to use it, and you have a tracker of open items.",
    why_it_matters: "Weekend 7 was about creating output; this is about managing input. Two automations (content + productivity) creates a minimum viable automation stack.",
    sort_order: 8,
  },
  {
    number: 9,
    title: "The Context Engineering Project",
    subtitle: "Build Your Personal AI Operating System",
    deliverable: "A structured personal context system + a Professional Context Document for pasting.",
    description_work: "AI OS Structure: Create sections in Notion/Obsidian: Playbook, Artifacts Library, Automation Log, & Decisions Log. Capture Habit: Set up one central inbox for AI notes and a 15-minute weekly review. Context Doc: Write your Role, Key Projects, Style preferences, and a 'What to Avoid' list. Deploy: Save the Context Doc where you can copy-paste it instantly.",
    description_advanced: "Create multiple context profiles (e.g., separate Work vs. Personal). Include actual examples of your writing/emails in the context file. Build a quarterly context refresh into your calendar.",
    done_when: "You have one place to store/reuse outputs, a Context Doc that improves chats, and a habit to maintain it.",
    why_it_matters: "The gap between 'using AI' and 'having AI that knows your context' is enormous. Most people re-explain their situation every single conversation.",
    sort_order: 9,
  },
  {
    number: 10,
    title: "The AI-Powered Build",
    subtitle: "Build Something with AI Inside It",
    deliverable: "A working application that uses AI as a core feature — a chatbot, voice agent, or tool.",
    description_work: "Platform: Use Google AI Studio or similar to build the core logic. Option A (Knowledge): Build a chatbot trained on your expertise, notes, or FAQs. Option B (Voice): Build a voice agent for practice (language, interviews, sales). Option C (Mini-Agent): Ingest docs → extract info → output structured data. Deploy: Ship it somewhere usable, even if just for yourself.",
    description_advanced: "Build something for others (team/clients), not just you. Train it on a specific company knowledge base. Give it to real people, get feedback, and iterate. Move from 'side project' to 'prototype'.",
    done_when: "You've built and deployed something that has AI at its center, and you (or someone else) can actually use it.",
    why_it_matters: "Weekend 1 used AI to help you build. This weekend is building something that uses AI. You're not just a user anymore — you're building AI-powered tools.",
    sort_order: 10,
  },
  {
    number: 0,
    title: "The Agent Exploration",
    subtitle: "Run the Agent Evaluation Gauntlet",
    deliverable: "Agent Scorecard + Use Cases document.",
    description_work: "Research + Synthesis: Process 8 links/docs into a brief. Identify missing info. Operations Task: Turn notes into a checklist with timeline & roles. Production Task: Generate summary, email, 5 posts, & overview. Evaluate across: Accuracy & Hallucination, Instruction Following, Output Usefulness, Repeatability.",
    description_advanced: "Build your own simple agent using a framework like CrewAI or AutoGen. Peek under the hood.",
    done_when: "You can answer: Which tasks are safe to delegate unsupervised? Which need human-in-the-loop?",
    why_it_matters: "Agents are the future. Moving from 'chatbot' to 'agent' mental models requires hands-on stress testing to know limits.",
    sort_order: 11,
  },
];
